# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNcamerademo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNcamerademo
  pod 'React', path: '../node_modules/react-native', subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]

  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'react-native-camera', path: '../node_modules/react-native-camera', subspecs: [
    'TextDetector'
  ]

  # pod 'react-native-camera', path: '../node_modules/react-native-camera'
  

  # target 'RNcamerademo-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

  # target 'RNcamerademoTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

end

# target 'RNcamerademo-tvOS' do
#   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   # use_frameworks!

#   # Pods for RNcamerademo-tvOS

#   target 'RNcamerademo-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end

# end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
